name: Patrik Svensson
favicon: null
layout_spectrum: 1
typography_spectrum: 0.7231755228713155
title: Patrik Svenssson
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#a99e9c'
    - '#d5cbc9'
    - '#3f383f'
    - '#1d181f'
    - '#8d524a'
  brandStrength: 0.7093032810371369
  lightness: 0.04960154346190393
  saturation: 0.3752907421439886
  rhythmicContrast: 0.686486290069297
purpose: []
